### PR TITLE
Improve tutorial code

### PR DESCRIPTION
**Pull request by ambv**
This is a rather large change if you look at it in one diff. However, I split it in separate commits so you can see what's going on. It's making the code a bit more modern and provides some best practice fixes.

### CODE REVIEW

**Review by bitcraft — COMMENTED** [review]
Looks fine.  I would have preferred that you not remove the * imports and not introduced pathlib.

**Comment by bitcraft** [comment]
Thanks for the update and of course Black.

**Comment by ambv** [comment]
The * imports make static type checking impossible so we generally avoid them. LMK if you want me to reintroduce them.

What's wrong with `pathlib`? The code looks cleaner to me that way but obviously you're the maintainer here.

**Comment by bitcraft** [comment]
The static imports just look like clutter when there are too many.  The
cleanest way to remove the star import would have been to import the
correct namespace... I think it is pygame.key.

I think the operator overloading aspect of pathlib is too clever and looks
clunky to me.   Unfortunately I am in the minority with pathlib.  People
like shiny new things.  I prefer a functional interface like os.path.join.

No need to revert your changes.  These are just trivial changes for a small
demonstration file.  Some people feel strongly about new features and
putting them into the demo is appealing to them.  Thank you.

**Pull request merged**
