### PR TITLE
Self advertisement added

### PR DESCRIPTION
**Pull request by Connor124**
### Am I actually allowed to do this?

I don't know.

### Is it worth a try?

Oh yes.

### CODE REVIEW

**Comment by bitcraft** [comment]
Unless you contribute code, I'm not going to add your name or project to the files.

**Comment by wkmanire** [comment]
lol, 

http://3.bp.blogspot.com/-VF6owpiHQVw/VHI3tG2FibI/AAAAAAAAhrY/3ZWlAooCuuw/s1600/get%2Bthe%2Bfuck%2Boutta%2Bhere.jpg

**Comment by Connor124** [comment]
Sorry, I just meant that a fully working game would be useful to us beginners as documentation is impossible. I have seen other implementations using Python2 and a renderer.py, but these stray too far from your example code. Any other projects are fine, it doesn't have to be mine, it's just the only one I could find.

**Comment by bitcraft** [comment]
I see what you mean, but I don't think that the source code is the right
place to list projects using pyscroll. The project wiki would be a better
place for that I think.

**Comment by Connor124** [comment]
And one other thing. A pygane.quit() should be put after the escape key press in the quest.py to ensure the window closes properly.

**Comment by Connor124** [comment]
OK, I improved the wiki quite a lot.

**Comment by bitcraft** [comment]
Thanks!  I'll update the readme to direct people to the wiki.

**Pull request closed without merging**
